# Generated by Django 3.0.6 on 2021-01-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0012_auto_20200511_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.IntegerField()),
                ('q_no', models.IntegerField()),
                ('quiz_start', models.DateTimeField()),
                ('quiz_endtime', models.DateTimeField()),
                ('points', models.IntegerField(default=10)),
            ],
            options={
                'ordering': ['-current_day', 'quiz_endtime'],
            },
        ),
        migrations.AlterModelOptions(
            name='myusers',
            options={'ordering': ['-score', 'lastcorrectans']},
        ),
        migrations.RenameField(
            model_name='myusers',
            old_name='pointsfactor',
            new_name='score',
        ),
        migrations.AddField(
            model_name='myusers',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='myusers',
            name='qno',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.CharField(max_length=5000)),
                ('islink', models.BooleanField(default=False)),
                ('link', models.CharField(max_length=450, null=True)),
                ('ispic', models.BooleanField(default=False)),
                ('image', models.URLField(max_length=1000, null=True)),
                ('answer', models.CharField(max_length=50)),
                ('day', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['day', 'order'],
                'unique_together': {('day', 'order')},
            },
        ),
    ]
